In [3]:
import numpy as np

np.ones((1,5)) / 10 + .4 # 1x5 matrix

array([[0.5, 0.5, 0.5, 0.5, 0.5]])

In [5]:
np.linspace(0, 10, 11) # 1x10 matrix 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.arange(0, 11, 1) # 1x10 matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.eye(5) # 5x5 Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.seed(42) # seed for reproducibility
print( np.random.rand(6) ) # random numbers from a uniform distribution
print( np.random.randn(6) )  # random numbers from a normal distribution
print( np.random.normal(0, 1, 6) )  # random numbers from a normal distribution
print( np.random.randint(1, 100, 6) ) # random integers between 1 and 10

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
[ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975]
[ 0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733]
[92 60 80 15 62 62]


In [ ]:
np.random.seed(63) # seed for reproducibility  -  Must be in the same cell as the random function to reproduce the same results
print( np.random.rand(6) ) # random numbers from a uniform distribution
print( np.random.randn(6) )  # random numbers from a normal distribution
print( np.random.normal(0, 1, 6) )  # random numbers from a normal distribution
print( np.random.randint(1, 100, 6) ) # random integers between 1 and 10

[0.55394102 0.39624789 0.04812677 0.52567256 0.15303858 0.50001016]
[ 0.29162807 -1.65065515 -1.50712909  0.26528183 -0.10140283 -0.86539089]
[ 0.71867687  1.07885403 -0.14180576  1.11263618 -0.0575936   0.00808383]
[53  7  5 78 31  6]


In [31]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 10, 21, 10, 26,  1,  6,  4, 45, 19], dtype=int32)

In [ ]:
arr.shape  # it is a 1D array!

(25,)

In [ ]:
arr.reshape(5,5) # now it became a 5x5 matrix
# The reshape you choose must be compatible with the number of elements in the original array!

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])